#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
# Exit code 100: Sqf validation failed
# Exit code 200: Config validiaton failed
# Exit code 300: Sqf and config validiaton failed

# Redirect output to stderr.
exec 1>&2

exit_code=0
git_path=`git rev-parse --show-toplevel`
cd "$git_path"
cd tools

# Validate sqf
python sqf_validator.py
result=$?

if (("$result" != 0)); then 
	exit_code=$((exit_code + 100))
fi

echo 
echo

# Validate config
python config_style_checker.py
result=$?

if (("$result" != 0)); then 
	exit_code=$((exit_code + 200))
fi

exit "$exit_code"